# Generated by Django 2.0.10 on 2019-02-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190204_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comm_num',
            field=models.IntegerField(default=0, verbose_name='评论数量'),
        ),
        migrations.AddField(
            model_name='blog',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='是否推荐'),
        ),
        migrations.AddField(
            model_name='blog',
            name='like_num',
            field=models.IntegerField(default=0, verbose_name='点赞数量'),
        ),
        migrations.AddField(
            model_name='blog',
            name='read_num',
            field=models.IntegerField(default=0, verbose_name='阅读数量'),
        ),
    ]
